# Generated by Django 5.0.6 on 2025-09-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=100)),
                ('cart', models.JSONField(null=True)),
                ('boxsize', models.CharField(max_length=30, null=True)),
                ('protein', models.CharField(max_length=30, null=True)),
                ('subprotein', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('currency', models.CharField(max_length=20)),
                ('tx_ref', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('delivery', models.DecimalField(decimal_places=2, default=500, max_digits=50)),
                ('cart_item_price', models.JSONField(null=True)),
                ('address', models.JSONField(null=True)),
                ('mobile', models.JSONField(null=True)),
                ('datetime', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
