# Generated by Django 5.0.6 on 2025-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='boxsize',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('preparing', 'preparing'), ('ready', 'ready'), ('out for delivery', 'out for delivery'), ('delivery', 'delivery')], max_length=100),
        ),
    ]
