# Generated by Django 4.2.3 on 2024-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(max_length=20),
        ),
    ]
