# Generated by Django 5.0.6 on 2025-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transactions_boxsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='order_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
