# Generated by Django 5.0.6 on 2025-10-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transactions_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cart',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cart_item_price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('preparing', 'preparing'), ('ready', 'ready'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], max_length=100),
        ),
    ]
