# Generated by Django 4.2.3 on 2024-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
