# Generated by Django 4.2.3 on 2024-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='userprotein',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
