# Generated by Django 4.2.3 on 2024-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transactions_userprotein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='userprotein',
            new_name='boxsize',
        ),
        migrations.AddField(
            model_name='transactions',
            name='protein',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subprotein',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
