# Generated by Django 4.2.3 on 2024-07-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_userprotein_transactions_boxsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='boxsize',
        ),
    ]
