# Generated by Django 4.2.3 on 2024-07-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_transactions_boxsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='boxsize',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
