# Generated by Django 4.2.3 on 2024-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transactions_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
