# Generated by Django 4.2.3 on 2024-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_archivedcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcart',
            name='cart',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='archivedcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
