# Generated by Django 4.2.3 on 2024-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_archivedcart_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cart',
            field=models.JSONField(blank=True, default=[{'cart_id': 311, 'content_type_id': 2, 'food_category': 'mini box', 'id': 848, 'object_id': 1, 'protein': 'beef', 'quantity': 15, 'subprotein': 'fried beef'}, {'cart_id': 311, 'content_type_id': 2, 'food_category': 'mini box', 'id': 850, 'object_id': 11, 'protein': 'beef', 'quantity': 12, 'subprotein': 'fried beef'}, {'cart_id': 311, 'content_type_id': 2, 'food_category': 'mini box', 'id': 851, 'object_id': 7, 'protein': 'beef', 'quantity': 3, 'subprotein': 'fried beef'}, {'cart_id': 311, 'content_type_id': 2, 'food_category': 'mini box', 'id': 852, 'object_id': 6, 'protein': 'beef', 'quantity': 9, 'subprotein': 'fried beef'}, {'cart_id': 311, 'content_type_id': 3, 'food_category': 'mini', 'id': 853, 'object_id': 50, 'protein': 'beef', 'quantity': 8, 'subprotein': 'fried beef'}], null=True),
        ),
        migrations.AlterField(
            model_name='archivedcart',
            name='cart',
            field=models.JSONField(),
        ),
    ]
