# Generated by Django 4.2.3 on 2024-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_transactions_cart_alter_archivedcart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cart',
            field=models.JSONField(null=True),
        ),
    ]
