# Generated by Django 4.2.3 on 2024-08-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_transactions_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedCart',
        ),
    ]
