# Generated by Django 4.2.3 on 2025-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_delete_archivedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='address',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='cart_item_price',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=50),
        ),
        migrations.AddField(
            model_name='transactions',
            name='mobile',
            field=models.JSONField(null=True),
        ),
    ]
