# Generated by Django 4.1.6 on 2023-07-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemsSoup',
        ),
    ]
