# Generated by Django 4.1.6 on 2023-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitemsfood_cart_alter_cartitemsfood_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemsfood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
