# Generated by Django 4.1.6 on 2023-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitemsfood_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemsfood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
