# Generated by Django 4.2.3 on 2023-08-13 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitemsfood_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='cartitemsfood',
            name='food_category',
            field=models.CharField(default='mini box', max_length=30),
        ),
    ]
