# Generated by Django 4.2.3 on 2024-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_useraddress_area_alter_useraddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(choices=[('ondo state', 'Ondo state')], max_length=200),
        ),
    ]
