# Generated by Django 4.2.3 on 2024-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_useraddress_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lcda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lga',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
