# Generated by Django 5.0.6 on 2025-09-07 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('food_item', models.CharField(max_length=30)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('protein_exist', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=30)),
                ('description', models.CharField(default='one complimentary tin milk', max_length=1000)),
                ('availability', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('soup_item', models.CharField(max_length=30)),
                ('mini_box_name', models.CharField(default='mini box', max_length=30)),
                ('mini_box_price', models.DecimalField(decimal_places=2, default=5000, max_digits=30)),
                ('medium_box_name', models.CharField(default='medium box', max_length=30)),
                ('medium_box_price', models.DecimalField(decimal_places=2, default=7000, max_digits=30)),
                ('mega_box_name', models.CharField(default='mega box', max_length=30)),
                ('mega_box_price', models.DecimalField(decimal_places=2, default=10000, max_digits=30)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('protein_exist', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=30)),
                ('description', models.CharField(default='one complimentary tin milk', max_length=1000)),
                ('availability', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=True, max_length=50)),
            ],
        ),
    ]
