# Generated by Django 4.2.3 on 2023-08-13 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_remove_soup_medium_box_remove_soup_mega_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soup',
            old_name='soup_price',
            new_name='mini_box_price',
        ),
        migrations.AddField(
            model_name='soup',
            name='medium_box_name',
            field=models.CharField(default='mini box', max_length=30),
        ),
        migrations.AddField(
            model_name='soup',
            name='medium_box_price',
            field=models.DecimalField(decimal_places=2, default=7000, max_digits=30),
        ),
        migrations.AddField(
            model_name='soup',
            name='mega_box_name',
            field=models.CharField(default='mini box', max_length=30),
        ),
        migrations.AddField(
            model_name='soup',
            name='mega_box_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=30),
        ),
        migrations.AddField(
            model_name='soup',
            name='mini_box_name',
            field=models.CharField(default='mini box', max_length=30),
        ),
        migrations.AddField(
            model_name='soup',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
