# Generated by Django 4.2.3 on 2023-09-16 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0013_soup_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
