# Generated by Django 4.2.3 on 2024-02-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_app', '0016_alter_soup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprotein', models.CharField(max_length=300)),
                ('subprotein2', models.CharField(max_length=300)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.protein')),
            ],
        ),
        migrations.CreateModel(
            name='UserProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.protein')),
                ('subprotein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.subprotein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
