# Generated by Django 4.2.3 on 2024-02-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0019_remove_subprotein_subprotein2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprotein',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.protein'),
        ),
        migrations.AlterField(
            model_name='userprotein',
            name='subprotein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.subprotein'),
        ),
    ]
