# Generated by Django 4.2.3 on 2024-06-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0020_alter_userprotein_protein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soup',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='uid',
        ),
    ]
