# Generated by Django 4.2.3 on 2024-06-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0021_remove_soup_protein_remove_soup_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='uid',
        ),
    ]
