# Generated by Django 4.2.3 on 2025-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0023_remove_subprotein_protein_remove_userprotein_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='one complimetary tin milk', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='protein_exist',
            field=models.CharField(default='yes', max_length=30),
        ),
    ]
