# Generated by Django 4.2.3 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0025_soup_description_soup_protein_exist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='availability',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='soup',
            name='availability',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default=True, max_length=50),
        ),
    ]
