# Generated by Django 4.2.3 on 2024-01-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
    ]
