# Generated by Django 4.2.3 on 2024-06-25 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
