# Generated by Django 4.0.4 on 2022-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=30)),
                ('food_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soup_item', models.CharField(max_length=30)),
                ('mini_box', models.IntegerField()),
                ('medium_box', models.IntegerField()),
                ('mega_box', models.IntegerField()),
            ],
        ),
    ]
