# Generated by Django 4.2.3 on 2023-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_food_food_price_alter_soup_medium_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soup',
            name='medium_box',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='mega_box',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='mini_box',
        ),
        migrations.AddField(
            model_name='soup',
            name='soup_price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=30),
        ),
    ]
