# Generated by Django 4.2.3 on 2023-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_rename_soup_price_soup_mini_box_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.CharField(default='boiled chicken', max_length=50),
        ),
        migrations.AddField(
            model_name='soup',
            name='protein',
            field=models.CharField(default='boiled chicken', max_length=50),
        ),
    ]
