# Generated by Django 4.2.3 on 2023-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_food_protein_soup_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='uid',
        ),
    ]
