# Generated by Django 4.2.3 on 2023-09-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0010_protein_subprotein_userprotein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprotein',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='userprotein',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userprotein',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='userprotein',
            name='subprotein',
        ),
        migrations.RemoveField(
            model_name='userprotein',
            name='user',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='SubProtein',
        ),
        migrations.DeleteModel(
            name='UserProtein',
        ),
    ]
