# Generated by Django 4.2.3 on 2023-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_remove_subprotein_protein_remove_userprotein_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.CharField(default='fried beef', max_length=100),
        ),
        migrations.AddField(
            model_name='soup',
            name='protein',
            field=models.CharField(default='boiled beef', max_length=100),
        ),
    ]
