# Generated by Django 4.2.3 on 2023-09-16 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0012_food_protein_soup_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='soup',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
