# Generated by Django 4.2.3 on 2023-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0014_food_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soup',
            name='medium_box_name',
            field=models.CharField(default='medium box', max_length=30),
        ),
        migrations.AlterField(
            model_name='soup',
            name='mega_box_name',
            field=models.CharField(default='mega box', max_length=30),
        ),
    ]
