# Generated by Django 4.2.3 on 2024-02-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0017_protein_subprotein_userprotein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprotein',
            name='protein',
            field=models.ForeignKey(default='beef', on_delete=django.db.models.deletion.CASCADE, to='food_app.protein'),
        ),
        migrations.AlterField(
            model_name='userprotein',
            name='subprotein',
            field=models.ForeignKey(default='fried beef', on_delete=django.db.models.deletion.CASCADE, to='food_app.subprotein'),
        ),
    ]
