# Generated by Django 4.2.3 on 2024-02-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0018_alter_userprotein_protein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprotein',
            name='subprotein2',
        ),
    ]
